
import { User, UserRole, Project, ScholarshipTable, Specialist, Candidate, HRMember } from '../types/legacy';

export const mockUsers: User[] = [
  { id: '1', name: 'Gestor do Polo', email: 'gestor@polo.com', role: UserRole.GESTOR, isServidor: true },
  { id: 't1', name: 'Usuário Teste', email: 'usuario.teste@polo.com', role: UserRole.GESTOR, isServidor: true },
  { id: '2', name: 'Dr. Roberto Santos', email: 'roberto.santos@if.edu.br', role: UserRole.COORDENADOR, isServidor: true },
  { id: '3', name: 'Dra. Ana Costa', email: 'ana.costa@if.edu.br', role: UserRole.COORDENADOR, isServidor: true },
];

export const mockScholarshipTables: ScholarshipTable[] = [
  {
    id: 'v1',
    version: '2024.1 - Vigente',
    active: true,
    categories: { junior: 2000, pleno: 4000, master: 6000 }
  }
];

export const mockSpecialists: Specialist[] = [
  { id: 's1', name: 'João Silva', email: 'joao.silva@if.edu.br', isServidor: true, currentWorkload: 40 },
  { id: 's2', name: 'Maria Souza', email: 'maria.souza@if.edu.br', isServidor: true, currentWorkload: 20 },
  { id: 's3', name: 'Pedro Oliver', email: 'pedro.oliver@ext.com', isServidor: false, currentWorkload: 0 },
];

export const mockCandidates: Candidate[] = [
  { id: 'c1', name: 'Lucas Amado', score: 95, suggestedCategory: 'Master' },
  { id: 'c2', name: 'Carla Dias', score: 82, suggestedCategory: 'Pleno' },
  { id: 'c3', name: 'Bernardo Silva', score: 45, suggestedCategory: 'Junior' },
];

export let mockProjects: Project[] = [
  {
    id: 'P2024-001',
    title: 'Desenvolvimento de Baterias de Sódio',
    acronym: 'SODIUM-BAT',
    objectDescription: 'Pesquisa e desenvolvimento de células de bateria baseadas em sódio para armazenamento estacionário.',
    startDate: '2024-01-01',
    endDate: '2025-12-31',
    companies: ['EnergiaBr', 'VoltStart'],
    resources: [
      { source: 'Empresa', value: 500000 },
      { source: 'Embrapii', value: 300000 }
    ],
    piRule: 'COMPARTILHADA',
    annexes: ['acordo_parceria.pdf'],
    coordinatorId: '2',
    totalValue: 800000
  },
  {
    id: 'P2024-002',
    title: 'Monitoramento Termográfico em Redes Elétricas',
    acronym: 'TERM-SCAN',
    objectDescription: 'Sistema de detecção proativa de falhas via análise térmica em tempo real.',
    startDate: '2024-03-01',
    endDate: '2025-03-01',
    companies: ['Norte Energia'],
    resources: [
      { source: 'Empresa', value: 450000 }
    ],
    piRule: 'EXCLUSIVA_IF',
    annexes: ['termo_confidencialidade.pdf'],
    coordinatorId: '2',
    totalValue: 450000
  },
  {
    id: 'P2024-003',
    title: 'Plataforma de IoT para Gestão de Resíduos',
    acronym: 'WASTE-TECH',
    objectDescription: 'Otimização de rotas e coleta seletiva através de sensores ultrassônicos.',
    startDate: '2023-10-01',
    endDate: '2024-10-01',
    companies: ['Sustenta Brasil', 'Prefeitura de JP'],
    resources: [
      { source: 'IFPB', value: 150000 },
      { source: 'Sebrae', value: 100000 }
    ],
    piRule: 'COMPARTILHADA',
    annexes: ['projeto_executivo.pdf'],
    coordinatorId: '3',
    totalValue: 250000
  },
  {
    id: 'P2024-004',
    title: 'IA Aplicada ao Diagnóstico Oncológico',
    acronym: 'VITA-AI',
    objectDescription: 'Redes neurais para auxílio na detecção precoce de anomalias em exames de imagem.',
    startDate: '2024-06-01',
    endDate: '2026-06-01',
    companies: ['Hospital Premium', 'MedCloud'],
    resources: [
      { source: 'Embrapìi', value: 600000 },
      { source: 'Empresa', value: 400000 }
    ],
    piRule: 'COMPARTILHADA',
    annexes: ['etica_pesquisa.pdf'],
    coordinatorId: '2',
    totalValue: 1000000
  }
];

export let mockHRMembers: HRMember[] = [
  {
    id: 'h1',
    name: 'João Silva',
    projectId: 'P2024-001',
    role: 'Pesquisador Sênior',
    category: 'Master',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    hoursPerMonth: 40,
    paymentSource: ['Embrapii'],
    scholarshipValue: 6000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h2',
    name: 'Maria Souza',
    projectId: 'P2024-001',
    role: 'Pesquisador Pleno',
    category: 'Pleno',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 4000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h3',
    name: 'Ricardo Ramos',
    projectId: 'P2024-001',
    role: 'Desenvolvedor Full Stack',
    category: 'Pleno',
    startDate: '2024-02-01',
    endDate: '2024-12-31',
    hoursPerMonth: 40,
    paymentSource: ['Embrapii'],
    scholarshipValue: 4000,
    installments: 11,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h4',
    name: 'Fernanda Lima',
    projectId: 'P2024-001',
    role: 'Designer UI/UX',
    category: 'Junior',
    startDate: '2024-03-01',
    endDate: '2024-12-31',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 2000,
    installments: 10,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h5',
    name: 'Gustavo Henrique',
    projectId: 'P2024-001',
    role: 'Pesquisador Júnior',
    category: 'Junior',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 2000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h6',
    name: 'Beatriz Santos',
    projectId: 'P2024-001',
    role: 'Analista de Testes',
    category: 'Junior',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    hoursPerMonth: 20,
    paymentSource: ['Embrapii'],
    scholarshipValue: 2000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h7',
    name: 'Thiago Silva',
    projectId: 'P2024-001',
    role: 'Mestre em Engenharia',
    category: 'Master',
    startDate: '2024-01-01',
    endDate: '2025-01-01',
    hoursPerMonth: 40,
    paymentSource: ['Embrapii'],
    scholarshipValue: 6000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h8',
    name: 'Aline Ferreira',
    projectId: 'P2024-001',
    role: 'Especialista Químico',
    category: 'Pleno',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    hoursPerMonth: 30,
    paymentSource: ['Empresa'],
    scholarshipValue: 4000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h9',
    name: 'Rafael Castro',
    projectId: 'P2024-002',
    role: 'Coordenador Técnico',
    category: 'Master',
    startDate: '2024-03-01',
    endDate: '2025-03-01',
    hoursPerMonth: 40,
    paymentSource: ['Empresa'],
    scholarshipValue: 6000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h10',
    name: 'Patricia Gomes',
    projectId: 'P2024-002',
    role: 'Especialista em Termografia',
    category: 'Pleno',
    startDate: '2024-03-01',
    endDate: '2025-03-01',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 4000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h11',
    name: 'Marcelo Diniz',
    projectId: 'P2024-002',
    role: 'Desenvolvedor Pleno',
    category: 'Pleno',
    startDate: '2024-04-01',
    endDate: '2025-03-01',
    hoursPerMonth: 40,
    paymentSource: ['Empresa'],
    scholarshipValue: 4000,
    installments: 11,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h12',
    name: 'Leticia Almeida',
    projectId: 'P2024-002',
    role: 'Analista de Infraestrutura',
    category: 'Junior',
    startDate: '2024-03-01',
    endDate: '2025-03-01',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 2000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h13',
    name: 'Gabriel Braga',
    projectId: 'P2024-002',
    role: 'Pesquisador Visitante',
    category: 'Junior',
    startDate: '2024-05-01',
    endDate: '2025-03-01',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 2000,
    installments: 10,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h14',
    name: 'Vanessa Rocha',
    projectId: 'P2024-002',
    role: 'Technical Lead',
    category: 'Master',
    startDate: '2024-03-01',
    endDate: '2025-03-01',
    hoursPerMonth: 10,
    paymentSource: ['Empresa'],
    scholarshipValue: 6000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h15',
    name: 'Igor Nascimento',
    projectId: 'P2024-002',
    role: 'Cientista de Dados',
    category: 'Pleno',
    startDate: '2024-03-01',
    endDate: '2025-03-01',
    hoursPerMonth: 40,
    paymentSource: ['Empresa'],
    scholarshipValue: 4000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h16',
    name: 'Camila Vieira',
    projectId: 'P2024-002',
    role: 'Engenheira de Software',
    category: 'Junior',
    startDate: '2024-03-01',
    endDate: '2024-12-31',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 2000,
    installments: 10,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h17',
    name: 'Vinicius Souza',
    projectId: 'P2024-003',
    role: 'Arquiteto de Soluções IoT',
    category: 'Master',
    startDate: '2023-10-01',
    endDate: '2024-10-01',
    hoursPerMonth: 20,
    paymentSource: ['IFPB'],
    scholarshipValue: 6000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h18',
    name: 'Natalia Lima',
    projectId: 'P2024-003',
    role: 'Desenvolvedora Pleno',
    category: 'Pleno',
    startDate: '2023-11-01',
    endDate: '2024-10-01',
    hoursPerMonth: 40,
    paymentSource: ['Sebrae'],
    scholarshipValue: 4000,
    installments: 11,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h19',
    name: 'Eduardo Santos',
    projectId: 'P2024-003',
    role: 'Analista de Redes',
    category: 'Junior',
    startDate: '2023-10-01',
    endDate: '2024-10-01',
    hoursPerMonth: 20,
    paymentSource: ['IFPB'],
    scholarshipValue: 2000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h20',
    name: 'Sophia Oliver',
    projectId: 'P2024-003',
    role: 'Designer de Hardware',
    category: 'Junior',
    startDate: '2024-01-01',
    endDate: '2024-10-01',
    hoursPerMonth: 20,
    paymentSource: ['Sebrae'],
    scholarshipValue: 2000,
    installments: 9,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h21',
    name: 'Arthur Silva',
    projectId: 'P2024-003',
    role: 'Especialista em Resíduos',
    category: 'Pleno',
    startDate: '2023-10-01',
    endDate: '2024-10-01',
    hoursPerMonth: 10,
    paymentSource: ['IFPB'],
    scholarshipValue: 4000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h22',
    name: 'Helena Costa',
    projectId: 'P2024-003',
    role: 'Desenvolvedora Pleno',
    category: 'Pleno',
    startDate: '2023-10-01',
    endDate: '2024-10-01',
    hoursPerMonth: 40,
    paymentSource: ['Sebrae'],
    scholarshipValue: 4000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h23',
    name: 'Miguel Pereira',
    projectId: 'P2024-003',
    role: 'Analista Administrativo',
    category: 'Junior',
    startDate: '2024-02-01',
    endDate: '2024-10-01',
    hoursPerMonth: 20,
    paymentSource: ['IFPB'],
    scholarshipValue: 2000,
    installments: 8,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h24',
    name: 'Laura Ferreira',
    projectId: 'P2024-003',
    role: 'Gestora de Projetos',
    category: 'Master',
    startDate: '2023-10-01',
    endDate: '2024-10-01',
    hoursPerMonth: 20,
    paymentSource: ['IFPB'],
    scholarshipValue: 6000,
    installments: 12,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h25',
    name: 'Davi Oliveira',
    projectId: 'P2024-004',
    role: 'Cientista de Dados Sênior',
    category: 'Master',
    startDate: '2024-06-01',
    endDate: '2026-06-01',
    hoursPerMonth: 40,
    paymentSource: ['Embrapìi'],
    scholarshipValue: 6000,
    installments: 24,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h26',
    name: 'Alice Santos',
    projectId: 'P2024-004',
    role: 'Desenvolvedora IA Pleno',
    category: 'Pleno',
    startDate: '2024-06-01',
    endDate: '2025-06-01',
    hoursPerMonth: 40,
    paymentSource: ['Empresa'],
    scholarshipValue: 4000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h27',
    name: 'Enzo Rodrigues',
    projectId: 'P2024-004',
    role: 'Analista de Dados',
    category: 'Junior',
    startDate: '2024-07-01',
    endDate: '2025-07-01',
    hoursPerMonth: 20,
    paymentSource: ['Embrapìi'],
    scholarshipValue: 2000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h28',
    name: 'Isabella Lima',
    projectId: 'P2024-004',
    role: 'Especialista em Imagem Mérica',
    category: 'Master',
    startDate: '2024-06-01',
    endDate: '2026-06-01',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 6000,
    installments: 24,
    source: 'SPECIALIST_BANK'
  },
  {
    id: 'h29',
    name: 'Beto Carvalho',
    projectId: 'P2024-004',
    role: 'Desenvolvedor Frontend',
    category: 'Pleno',
    startDate: '2024-06-01',
    endDate: '2026-06-01',
    hoursPerMonth: 40,
    paymentSource: ['Embrapìi'],
    scholarshipValue: 4000,
    installments: 24,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h30',
    name: 'Giovanna Souza',
    projectId: 'P2024-004',
    role: 'Cientista Júnior',
    category: 'Junior',
    startDate: '2024-08-01',
    endDate: '2025-08-01',
    hoursPerMonth: 20,
    paymentSource: ['Embrapìi'],
    scholarshipValue: 2000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h31',
    name: 'Cauã Nascimento',
    projectId: 'P2024-004',
    role: 'Auxiliar de Pesquisa',
    category: 'Junior',
    startDate: '2024-06-01',
    endDate: '2025-06-01',
    hoursPerMonth: 20,
    paymentSource: ['Empresa'],
    scholarshipValue: 2000,
    installments: 12,
    source: 'PROCESS_SELECT'
  },
  {
    id: 'h32',
    name: 'Lorena Silva',
    projectId: 'P2024-004',
    role: 'Consultora de Ética',
    category: 'Master',
    startDate: '2024-06-01',
    endDate: '2024-12-31',
    hoursPerMonth: 10,
    paymentSource: ['Embrapìi'],
    scholarshipValue: 6000,
    installments: 7,
    source: 'SPECIALIST_BANK'
  }
];
